In [ ]:
!pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.3.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: narwhals>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.18.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.0.2)
Downloading pyreadstat-1.3.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 13.0 MB/s eta 0:00:00
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.3.3

In [ ]:
import numpy as np
import pandas as pd
import pyreadstat
import os

In [ ]:
geda, meta =pyreadstat.read_sav("/content/GEDA19_cf.sav")
print(geda.shape)
geda.head()

(11354, 309)

,studie,sex,gender,age5B,age10B,agegrp1,agegrp2,agegrp3,agegrp4,agegrp5,...,SDbesthv2,SDjobstatB,SDft_ptB,SDmainstatB,MIdeutsch,MIbirthplace,MIbirthplacemoth_k,MIbirthplacefath_k,MIcitizen,MImigrant
0,31.0,2.0,2.0,8.0,5.0,2.0,1.0,5.0,4.0,5.0,...,NaN,20.0,2.0,10.0,1.0,10.0,10.0,10.0,10.0,2.0
1,31.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,...,NaN,20.0,1.0,10.0,1.0,10.0,10.0,10.0,10.0,2.0
2,31.0,1.0,1.0,9.0,5.0,2.0,1.0,5.0,4.0,5.0,...,NaN,20.0,1.0,10.0,1.0,10.0,10.0,10.0,10.0,2.0
3,31.0,2.0,2.0,14.0,8.0,3.0,2.0,7.0,7.0,8.0,...,NaN,NaN,NaN,30.0,1.0,10.0,10.0,10.0,10.0,2.0
4,31.0,1.0,1.0,5.0,3.0,1.0,1.0,3.0,2.0,3.0,...,3.0,NaN,NaN,80.0,1.0,10.0,10.0,10.0,10.0,2.0

In [ ]:
print(geda.columns.tolist()[:150])

['studie', 'sex', 'gender', 'age5B', 'age10B', 'agegrp1', 'agegrp2', 'agegrp3', 'agegrp4', 'agegrp5', 'agegrp6', 'agegrp7', 'agegrp8', 'agegrp9', 'agegrp10', 'agegrp11', 'agegrp12', 'untm', 'untj', 'bulasa', 'gkpol', 'gkpol4', 'ktyp4', 'ns3', 'reg4', 'reg5', 'reg5b', 'reg6', 'reg7', 'wo1', 'wo2', 'wob', 'wQS', 'wQSpop', 'KHhyp12', 'KHmyo12', 'KHkhk12', 'KHbbmyo12', 'KHmyokhk12', 'KHsa12', 'KHbbsa12', 'KHdiabB12', 'KHab12', 'KHlip12A', 'KHcb12B', 'KHlz12', 'KHniB12', 'KHdge12', 'KHalgi112', 'GZmehm1', 'GZmehm3C', 'GZmehm2D', 'GZmehm1_k', 'GZmehm1_k3', 'GZmehm2D_k', 'GZmehm2D_k2', 'SHseh1', 'SHseh2C', 'SHhoer1', 'SHhoer5', 'SHhoer6', 'SHbblimit_k', 'SHsehlimit_k', 'SHbblimit2_k', 'SHhoerlimit_k', 'SHsehkorr_k', 'SHseh1_k', 'BBmyo12', 'BBsa12', 'BBdors112', 'BBdors212', 'BBblas12B', 'BBgehen', 'BBtreppe', 'BBkonz1', 'BBessen', 'BBschwierig1', 'BBschwierig2', 'BBschwierig3', 'BBschwierig4', 'BBschwierig5', 'BBhilfe1', 'BBhilfe2', 'BBhh1', 'BBhh3', 'BBhh4', 'BBhh5', 'BBhh6', 'BBhh7', 'BBhhhilfe1', 'BBhhhilfe2', 'BBgehlimit_k', 'BBkonzlimit_k', 'BBesslimit_k', 'BBcarelimit_k', 'BBlimitA_k', 'BBlimitB_k', 'BBlimitC_k', 'BBlimitD_k', 'BBlimitE_k', 'BBhilfe_k', 'BBhhlimit_k', 'BBhhlimitA_k', 'BBhhlimitB_k', 'BBhhlimitC_k', 'BBhhlimitD_k', 'BBhhlimitE_k', 'BBhhlimitF_k', 'BBhhlimitG_k', 'BBhhhilfe_k', 'BBtotallimit_k', 'BBtotalhilfe_k', 'UVartverkehr', 'UVarthaus', 'UVartfreiz', 'UVarztF', 'UVarztF_k', 'UVsturz12', 'UVsturz12z', 'UVsturzang', 'UVsturz12mf', 'PKdep12', 'PKphqsum_k1', 'PKphqsum_k2', 'PKphq8sum', 'PKphq8_k1', 'PKphq8_k2', 'PKphq8_k3', 'PKphq8diag', 'PKphq8_k4', 'PKphq8_k5', 'PKphq8_k6', 'SFoslo1C', 'SFoslo2C', 'SFoslo3A', 'SFosloA', 'LQsf367C', 'LQsf368C', 'IAhypus', 'IAcholus', 'IAdiabus', 'IAtermin', 'IAweg', 'IAkosten1', 'IAkosten2', 'IAkosten3', 'IAkosten4', 'IAkosten', 'IAzugang', 'IAarzt14B_k']

In [ ]:
#Searching for the actual labels i need
labels=meta.column_names_to_labels

search_terms =[
    "diab",
    "smok",
    "phys",
    "activ",
    "bmi",
    "body mass",
    "blood pressure",
    "hypertension",
    "sport",
    "exercise"
]

for term in search_terms:
    matches ={k: v for k, v in labels.items() if isinstance(v, str) and term.lower() in v.lower()}
    print(f"\n--- SEARCH TERM: {term} ---")
    for k,v in list(matches.items())[:30]:
        print(k, "->", v)

--- SEARCH TERM: diab ---
KHdiabB12 -> Diabetes: I.d.l.12 Mon.

--- SEARCH TERM: smok ---

--- SEARCH TERM: phys ---
IAther2B -> Besuch Physiotherapeuten i.d.l. 12 Mon.

--- SEARCH TERM: activ ---

--- SEARCH TERM: bmi ---
GVindexsum -> Anzahl Verhaltensweisen mit erreichter Empfehlung (BMI, EN, KA, AK, RC)
PAbmiB_k -> BMI-Gruppierung (aus Selbstangabe Gewicht u. Größe), in 4 Kategorien
PAbmiB_k2 -> BMI-Gruppierung (aus Selbstangabe Gewicht u. Größe), in 6 Kategorien
PAadiposB -> Adipositas nach WHO (BMI>=30; aus Selbstangabe Gewicht u. Größe)
PAueberB -> Übergewicht nach WHO (BMI>=25; aus Selbstangabe Gewicht u. Größe)
PAnormalB -> Normalgewicht (18,5 <= BMI < 25; aus Selbstangabe Gewicht u. Größe)

--- SEARCH TERM: body mass ---

--- SEARCH TERM: blood pressure ---

--- SEARCH TERM: hypertension ---

--- SEARCH TERM: sport ---
KAehispaq6 -> Sport: Tage pro Woche
KAehispaq6_k -> Sport: (ohne körperliche Aktivität bei der Arbeit und um von Ort zu Ort zu gelangen)
KAtbka_k -> Transportbez. körp. Aktivität in MET (Energiever. in MET = Metabol. Äquivalent), (top coding ab 100h) kat. [Stunden/Woche]
KAspodauC_k -> Sport pro Woche insgesamt (in 30 min kategorisiert)

--- SEARCH TERM: exercise ---

In [ ]:
name_terms =["diab", "smok", "bmi", "bp", "hyper", "sport", "phys", "activ"]

for term in name_terms:
    matches =[ c for c in geda.columns if term.lower() in c.lower()]
    print("f\n---- VARIABLE NAME SEARCH: {term} ----")
    print(matches[:30])

f
---- VARIABLE NAME SEARCH: {term} ----
['KHdiabB12', 'IAdiabus']
f
---- VARIABLE NAME SEARCH: {term} ----
[]
f
---- VARIABLE NAME SEARCH: {term} ----
['PAbmiB_k', 'PAbmiB_k2']
f
---- VARIABLE NAME SEARCH: {term} ----
['PAhhnbpersk_0_4', 'PAhhnbpersk_5_13', 'PAhhnbpersk_14_15', 'PAhhnbpersk_16_24', 'PAhhnbpersk_25_64', 'PAhhnbpersk_65PLUS']
f
---- VARIABLE NAME SEARCH: {term} ----
[]
f
---- VARIABLE NAME SEARCH: {term} ----
[]
f
---- VARIABLE NAME SEARCH: {term} ----
[]
f
---- VARIABLE NAME SEARCH: {term} ----
[]

In [ ]:
possible_basic =["sex", "gender", "age", "age5B", "age10B", " age10B", "agegrp1", "agegrp2", "agegrp3", "agegrp4", "agegrp5"]

for col in possible_basic:
    if col in geda.columns:
      print(f"\n--- {col} ---")
      print(geda[col].value_counts(dropna=False).head(20))
      print("Label:", labels.get(col, "No label found"))

--- sex ---
sex
2.0    6005
1.0    5349
Name: count, dtype: int64
Label: Geschlecht

--- gender ---
gender
2.0    5988
1.0    5332
NaN      34
Name: count, dtype: int64
Label: Geschlechtsidentität

--- age5B ---
age5B
9.0     1286
11.0    1243
10.0    1241
8.0     1173
12.0     873
13.0     850
7.0      790
6.0      695
5.0      650
14.0     632
4.0      562
3.0      483
2.0      414
15.0     220
1.0      176
16.0      66
Name: count, dtype: int64
Label: Alter (5b-Jahres-Gruppen, gestutzt)

--- age10B ---
age10B
6.0    2484
5.0    2459
7.0    1723
4.0    1485
3.0    1212
2.0     897
8.0     852
1.0     176
9.0      66
Name: count, dtype: int64
Label: Alter (10-Jahres-Gruppen)

--- agegrp1 ---
agegrp1
3.0    5125
2.0    3944
1.0    2285
Name: count, dtype: int64
Label: Altersgruppe 1

--- agegrp2 ---
agegrp2
1.0    7470
2.0    3884
Name: count, dtype: int64
Label: Altersgruppe 2

--- agegrp3 ---
agegrp3
5.0    3700
7.0    2641
2.0    1459
3.0    1345
6.0    1243
4.0     790
1.0     176
Name: count, dtype: int64
Label: Altersgruppe 3

--- agegrp4 ---
agegrp4
5.0    2484
4.0    2459
6.0    1723
3.0    1485
2.0    1212
1.0    1073
7.0     918
Name: count, dtype: int64
Label: Altersgruppe 4

--- agegrp5 ---
agegrp5
6.0    2484
5.0    2459
7.0    1723
4.0    1485
3.0    1212
8.0     918
2.0     897
1.0     176
Name: count, dtype: int64
Label: Altersgruppe 5

In [ ]:
#Search using German words

german_terms =[
    "rauch", "rauchen", "tabak", "zig",
    "blutdruck", "hyperton", "hochdruck",
    "körper", "aktiv", "beweg", "sport",
    "diab", "gewicht", "adipos", "übergewicht"
]

for term in german_terms:
    matches ={k: v for k, v in labels.items() if isinstance(v, str) and term.lower() in v.lower()}
    print(f"\n --- GERMAN SEARCH TERM: {term}---")
    for k, v in list(matches.items())[:40]:
        print(k, "->", v)

 --- GERMAN SEARCH TERM: rauch---
RCstatE -> Rauchen
RCstatE_k2 -> Rauchstatus in 3 Kat.
RCstatE_k3 -> Aktuell Raucher
RCaktuell -> Kein aktuelles Rauchen
RCtgl1 -> Tgl. Rauchen v. fabrikfertigen/selbstgedrehten Zigaretten
RCzE_ttk -> Tgl. Raucher: Tgl. Anzahl Zigaretten (kat.)
RCzE_ttk2 -> Täglicher Zigarttenraucher (kat.)
RCtgl2 -> Tgl. Rauchen für mind. ein Jahr
RCpass4B_k -> Rauchen in geschlossenen Räumen in 2 Kat.
RCpass4B_k2 -> Rauchen in geschl. Räumen in 2 Kat. (nur NR)
RCpass4B -> Rauchen in geschlossenen Räumen
RCezig2 -> Rauchen v. elektr. Zigarette o. ähnlichen Produkten

 --- GERMAN SEARCH TERM: rauchen---
RCstatE -> Rauchen
RCaktuell -> Kein aktuelles Rauchen
RCtgl1 -> Tgl. Rauchen v. fabrikfertigen/selbstgedrehten Zigaretten
RCtgl2 -> Tgl. Rauchen für mind. ein Jahr
RCpass4B_k -> Rauchen in geschlossenen Räumen in 2 Kat.
RCpass4B_k2 -> Rauchen in geschl. Räumen in 2 Kat. (nur NR)
RCpass4B -> Rauchen in geschlossenen Räumen
RCezig2 -> Rauchen v. elektr. Zigarette o. ähnlichen Produkten

 --- GERMAN SEARCH TERM: tabak---
RCtgl2_jjk -> Dauer des täglichen Tabakkonsums (kat.)

 --- GERMAN SEARCH TERM: zig---
RCtgl1 -> Tgl. Rauchen v. fabrikfertigen/selbstgedrehten Zigaretten
RCzE_ttk -> Tgl. Raucher: Tgl. Anzahl Zigaretten (kat.)
RCzE_ttk2 -> Täglicher Zigarttenraucher (kat.)
RCezig2 -> Rauchen v. elektr. Zigarette o. ähnlichen Produkten

 --- GERMAN SEARCH TERM: blutdruck---
IAhypus -> Letzte Blutdruckmessung

 --- GERMAN SEARCH TERM: hyperton---
KHhyp12 -> Hypertonie: I.d.l.12 Mon.

 --- GERMAN SEARCH TERM: hochdruck---

 --- GERMAN SEARCH TERM: körper---
SHbblimit_k -> Körperliche u. sensorische, funktionale Einschränkungen (kat.)
BBhilfe1 -> Körperpflege etc.: Hilfe bei Tätigkeiten
BBhilfe2 -> Körperpflege etc.: (Mehr) Hilfe benötigt
BBcarelimit_k -> Schwierigkeiten bei der Körperpflege (kat.)
BBhilfe_k -> Bedarf an Hilfe bei der Körperpflege (kat.)
BBtotallimit_k -> Schwierigkeiten bei der Körperpflege u. im Haushalt (kat.)
BBtotalhilfe_k -> Bedarf an Hilfe bei der Körperpflege u. im Haushalt (kat.)
KAehispaq6_k -> Sport: (ohne körperliche Aktivität bei der Arbeit und um von Ort zu Ort zu gelangen)
KAaerob1_k -> Gesundheitsfördernde (Freizeit-) körperliche Aktivität (ohne Gehen) kat.
KAsabka -> Sehr anstrengende arbeitsbezogene körperliche Aktivität

 --- GERMAN SEARCH TERM: aktiv---
KAehispaq6_k -> Sport: (ohne körperliche Aktivität bei der Arbeit und um von Ort zu Ort zu gelangen)
KAtbka_k -> Transportbez. körp. Aktivität in MET (Energiever. in MET = Metabol. Äquivalent), (top coding ab 100h) kat. [Stunden/Woche]
KAaerob_k -> Aerobe körp. Aktivität (mit Gehen und Fahrrad fahren) [Min]
KAgfka -> Einhalt. aerobe WHO-Bew.empf. (mit Gehen >= 150 Min. aerobe körp. Aktiv./Wo)
KAaerob1_k -> Gesundheitsfördernde (Freizeit-) körperliche Aktivität (ohne Gehen) kat.
KAgfkaB -> Einhalt. aerobe WHO-Bew.empf. (o. Gehen >= 150 Min. aerobe körp. Aktiv./Wo)
KAgfmk -> WHO-Empf. zur Muskelkräft. (>= 2x/Wo. Aktivit. zur Muskelkräftigung)
KAgfa -> >= 150 min Ausdaueraktiv.und 2 x/ Woche Aktiv. zur Muskelkräft.(Einhalt. beider WHO-Empf.)
KAabka -> Mäßig bis sehr anstrengende arbeitsbez. körp. Aktivität
KAsabka -> Sehr anstrengende arbeitsbezogene körperliche Aktivität
KAgka_k -> Gesamtaktivität (kategorisiert)
KAgka -> Ausreichend körp. aktiv während Arbeit oder Freizeit

 --- GERMAN SEARCH TERM: beweg---
KAehispaq2 -> Bewegung zu Fuß: Tage pro Woche
KAehispaq3 -> Bewegung zu Fuß: Dauer
KAehispaq4 -> Bewegung mit Fahrrad: Tage pro Woche
KAehispaq5 -> Bewegung mit Fahrrad: Dauer
KAehispaq2_k -> Bewegung zu Fuß: Laufen um von Ort zu Ort zu gelangen
KAehispaq4_k -> Bewegung mit Fahrrad: Fahrrad fahren um von Ort zu Ort zu gelangen

 --- GERMAN SEARCH TERM: sport---
KAehispaq6 -> Sport: Tage pro Woche
KAehispaq6_k -> Sport: (ohne körperliche Aktivität bei der Arbeit und um von Ort zu Ort zu gelangen)
KAtbka_k -> Transportbez. körp. Aktivität in MET (Energiever. in MET = Metabol. Äquivalent), (top coding ab 100h) kat. [Stunden/Woche]
KAspodauC_k -> Sport pro Woche insgesamt (in 30 min kategorisiert)

 --- GERMAN SEARCH TERM: diab---
KHdiabB12 -> Diabetes: I.d.l.12 Mon.

 --- GERMAN SEARCH TERM: gewicht---
wQS -> Gewichtung GEDA19 (ab 18 Jahre; normiert auf Stichprobenumfang)
wQSpop -> Gewichtung GEDA19 (ab 18 Jahre; normiert auf Bevölkerungsumfang)
PAbmiB_k -> BMI-Gruppierung (aus Selbstangabe Gewicht u. Größe), in 4 Kategorien
PAbmiB_k2 -> BMI-Gruppierung (aus Selbstangabe Gewicht u. Größe), in 6 Kategorien
PAadiposB -> Adipositas nach WHO (BMI>=30; aus Selbstangabe Gewicht u. Größe)
PAueberB -> Übergewicht nach WHO (BMI>=25; aus Selbstangabe Gewicht u. Größe)
PAnormalB -> Normalgewicht (18,5 <= BMI < 25; aus Selbstangabe Gewicht u. Größe)

 --- GERMAN SEARCH TERM: adipos---
PAadiposB -> Adipositas nach WHO (BMI>=30; aus Selbstangabe Gewicht u. Größe)

 --- GERMAN SEARCH TERM: übergewicht---
PAueberB -> Übergewicht nach WHO (BMI>=25; aus Selbstangabe Gewicht u. Größe)

In [ ]:
#Deciding on what variable is the better one
candidate_cols =["KHdiabB12", "IAdiabus"]

for col in candidate_cols:
  if col in geda.columns:
       print(f"\n---{col} ---")
       print("Label:", labels.get(col, "No label found"))
       print(geda[col].value_counts(dropna=False).head(20))

---KHdiabB12 ---
Label: Diabetes: I.d.l.12 Mon.
KHdiabB12
2.0    10292
1.0     1046
NaN       16
Name: count, dtype: int64

---IAdiabus ---
Label: Letzte Blutzuckermessung
IAdiabus
1.0    6916
2.0    2142
5.0     800
NaN     542
3.0     492
4.0     462
Name: count, dtype: int64

In [ ]:
#Inspecting BMI & Physical-activity candidates

candidate_cols =["PAbmiB_k", "PAbmiB_k2", "PAadiposB", "PAueberB", "PAnormalB","KAehispaq6", "KAehispaq6_k", "KAspodauC_k"]

for col in candidate_cols:
  if col in geda.columns:
       print(f"\n---{col} ---")
       print("Label:", labels.get(col, "No label found"))
       print(geda[col].value_counts(dropna=False).head(20))

---PAbmiB_k ---
Label: BMI-Gruppierung (aus Selbstangabe Gewicht u. Größe), in 4 Kategorien
PAbmiB_k
2.0    5037
3.0    4011
4.0    1970
1.0     196
NaN     140
Name: count, dtype: int64

---PAbmiB_k2 ---
Label: BMI-Gruppierung (aus Selbstangabe Gewicht u. Größe), in 6 Kategorien
PAbmiB_k2
2.0    5037
3.0    4011
4.0    1380
5.0     419
1.0     196
6.0     171
NaN     140
Name: count, dtype: int64

---PAadiposB ---
Label: Adipositas nach WHO (BMI>=30; aus Selbstangabe Gewicht u. Größe)
PAadiposB
2.0    9244
1.0    1970
NaN     140
Name: count, dtype: int64

---PAueberB ---
Label: Übergewicht nach WHO (BMI>=25; aus Selbstangabe Gewicht u. Größe)
PAueberB
1.0    5981
2.0    5233
NaN     140
Name: count, dtype: int64

---PAnormalB ---
Label: Normalgewicht (18,5 <= BMI < 25; aus Selbstangabe Gewicht u. Größe)
PAnormalB
2.0    6177
1.0    5037
NaN     140
Name: count, dtype: int64

---KAehispaq6 ---
Label: Sport: Tage pro Woche
KAehispaq6
0.0    3146
2.0    2170
3.0    1816
1.0    1551
7.0    1008
4.0     808
5.0     607
6.0     226
NaN      22
Name: count, dtype: int64

---KAehispaq6_k ---
Label: Sport: (ohne körperliche Aktivität bei der Arbeit und um von Ort zu Ort zu gelangen)
KAehispaq6_k
1.0    8186
0.0    3146
NaN      22
Name: count, dtype: int64

---KAspodauC_k ---
Label: Sport pro Woche insgesamt (in 30 min kategorisiert)
KAspodauC_k
0.0     3150
4.0     1338
2.0     1162
6.0     1049
8.0      671
3.0      600
10.0     552
12.0     448
1.0      309
5.0      293
14.0     290
20.0     270
16.0     218
7.0      199
9.0      130
NaN       95
24.0      92
11.0      61
18.0      60
28.0      55
Name: count, dtype: int64

In [ ]:
candidate_cols=[
    "KHdiabB12",
    "KHhyp12",
    "RCstatE_k3",
    "RCaktuell",
    "PAbmiB_k2",
    "KAehispaq6",
    "age10B",
    "sex"

]

for col in candidate_cols:
     if col in geda.columns:
      print(f"\n---{col}---")
      print("Label:", labels.get(col,"No label found"))
      print(geda[col].value_counts(dropna=False).head(20))

---KHdiabB12---
Label: Diabetes: I.d.l.12 Mon.
KHdiabB12
2.0    10292
1.0     1046
NaN       16
Name: count, dtype: int64

---KHhyp12---
Label: Hypertonie: I.d.l.12 Mon.
KHhyp12
2.0    7938
1.0    3370
NaN      46
Name: count, dtype: int64

---RCstatE_k3---
Label: Aktuell Raucher
RCstatE_k3
2.0    8959
1.0    2393
NaN       2
Name: count, dtype: int64

---RCaktuell---
Label: Kein aktuelles Rauchen
RCaktuell
1.0    8959
2.0    2393
NaN       2
Name: count, dtype: int64

---PAbmiB_k2---
Label: BMI-Gruppierung (aus Selbstangabe Gewicht u. Größe), in 6 Kategorien
PAbmiB_k2
2.0    5037
3.0    4011
4.0    1380
5.0     419
1.0     196
6.0     171
NaN     140
Name: count, dtype: int64

---KAehispaq6---
Label: Sport: Tage pro Woche
KAehispaq6
0.0    3146
2.0    2170
3.0    1816
1.0    1551
7.0    1008
4.0     808
5.0     607
6.0     226
NaN      22
Name: count, dtype: int64

---age10B---
Label: Alter (10-Jahres-Gruppen)
age10B
6.0    2484
5.0    2459
7.0    1723
4.0    1485
3.0    1212
2.0     897
8.0     852
1.0     176
9.0      66
Name: count, dtype: int64

---sex---
Label: Geschlecht
sex
2.0    6005
1.0    5349
Name: count, dtype: int64

I have identified the main harmonization candidates for the German analysis: a diabetes diagnosis variable, a hypertension diagnosis variable, a current smoking variable, a six category BMI variable, a binary sport-participation variable, grouped sex and age.

In [ ]:
#GEDA Cleaning
geda_sub =geda[[
    "KHdiabB12",
    "KHhyp12",
    "RCstatE_k3",
    "PAbmiB_k2",
    "KAehispaq6",
    "age10B",
    "sex"
]].copy()

print(geda_sub.shape)
geda_sub.head()

(11354, 7)

   KHdiabB12  KHhyp12  RCstatE_k3  PAbmiB_k2  KAehispaq6  age10B  sex
0        2.0      2.0         2.0        3.0         1.0     5.0  2.0
1        2.0      2.0         1.0        2.0         0.0     2.0  2.0
2        2.0      1.0         2.0        3.0         1.0     5.0  1.0
3        2.0      1.0         2.0        1.0         7.0     8.0  2.0
4        2.0      2.0         2.0        2.0         6.0     3.0  1.0

In [ ]:
#Recoding the variables

#Diabetes: 1=yes, 2=no
geda_sub["diabetes_binary"] =np.where(
    geda_sub["KHdiabB12"]==1.0, 1,
    np.where(geda_sub["KHdiabB12"] == 2.0, 0, np.nan)

)

#Hypertension: 1=yes, 2=no
geda_sub["hypertension"] =np.where(
    geda_sub["KHhyp12"]==1.0, 1,
    np.where(geda_sub["KHhyp12"] == 2.0, 0, np.nan)

)

#Current smoker: 1=yes, 2=no
geda_sub["current_smoker"] =np.where(
    geda_sub["RCstatE_k3"]==1.0, 1,
    np.where(geda_sub["RCstatE_k3"] == 2.0, 0, np.nan)

)

#BMI
geda_sub["bmi"] =geda_sub["PAbmiB_k2"]

#Physical activity, 0 days/week -->inactive and 1-7 days/week -->active
geda_sub["physically_active"] =np.where(
    geda_sub["KAehispaq6"]== 0.0, 0,
    np.where(geda_sub["KAehispaq6"]. between (1.0, 7.0), 1, np.nan)
)

#Age: grouped age
geda_sub["age"] =geda_sub["age10B"]

#Sex: assume 1=male, 2=female
geda_sub["sex_male"] =np.where(
    geda_sub["sex"]==1.0, 1,
     np.where(geda_sub["sex"] == 2.0, 0, np.nan)

)

In [ ]:
geda_clean= geda_sub[[
    "diabetes_binary",
    "age",
    "sex_male",
    "bmi",
    "hypertension",
    "current_smoker",
    "physically_active"
]].copy()

print(geda_clean.shape)
print("\nOutcome distribution:")
print(geda_clean["diabetes_binary"].value_counts(dropna=False))

print("\nMissingness per variable:")
print(geda_clean.isna().mean().sort_values())

geda_clean.head()

(11354, 7)

Outcome distribution:
diabetes_binary
0.0    10292
1.0     1046
NaN       16
Name: count, dtype: int64

Missingness per variable:
age                  0.000000
sex_male             0.000000
current_smoker       0.000176
diabetes_binary      0.001409
physically_active    0.001938
hypertension         0.004051
bmi                  0.012330
dtype: float64

,diabetes_binary,age,sex_male,bmi,hypertension,current_smoker,physically_active
0,0.0,5.0,0.0,3.0,0.0,0.0,1.0
1,0.0,2.0,0.0,2.0,0.0,1.0,0.0
2,0.0,5.0,1.0,3.0,1.0,0.0,1.0
3,0.0,8.0,0.0,1.0,1.0,0.0,1.0
4,0.0,3.0,1.0,2.0,0.0,0.0,1.0

In [ ]:
geda_clean.to_csv("/content/geda_clean.csv", index=False)
print("Saved GEDA cleaned file to /content/geda_clean.csv")

Saved GEDA cleaned file to /content/geda_clean.csv